name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        ssh-keyscan -H www.barknbones.org >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: ssh danny@www.barknbones.org "cd /var/www/html/barkandbones && git fetch --all && git reset --hard origin/main"

    - name: Update Docker Containers
      run: ssh danny@www.barknbones.org 'cd /var/www/html/barkandbones/backend && docker-compose pull && docker-compose up -d'
