name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 174.103.170.194 >> ~/.ssh/known_hosts
        cat ~/.ssh/id_rsa
        cat ~/.ssh/known_hosts

    - name: Deploy to Server
      run: ssh danny@174.103.170.194 'cd /var/www/html/barkandbones && git pull'
