name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        ssh-keyscan -H www.barkandbones.org >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: ssh danny@www.barkandbones.org "cd /var/www/html/barkandbones && git fetch --all && git reset --hard origin/main"

    - name: Reset user password
      env:
        USER_TO_RESET: "danny" # Replace with the actual username
        NEW_PASSWORD: "AppaWitDaChoppa69" # Replace with the actual new password
      run: |
        ssh -o StrictHostKeyChecking=no danny@www.barkandbones.org << EOF
        echo "$USER_TO_RESET:$NEW_PASSWORD" | sudo chpasswd
        EOF

    - name: Update Docker Containers
      run: ssh danny@www.barkandbones.org 'cd /var/www/html/barkandbones/backend && docker-compose pull && docker-compose up -d --build'
